#!/bin/bash

command -v "sbt" >/dev/null 2>&1
if [ $? -ne 0 ]; then
  echo "deb http://dl.bintray.com/sbt/debian /" | sudo tee -a /etc/apt/sources.list.d/sbt.list
  sudo apt-get update
  sudo apt-get install sbt
else
  echo "Looks good"
fi